name: insert into neon db
on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:
jobs:
  insert-data:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.NEON_API_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run insert script
        run: |
          python neon_inserts.py || echo "Script failed"
